// Generated by CoffeeScript 1.6.3
(function() {
  var ErrorHandler, stream,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  stream = require('stream');

  ErrorHandler = (function(_super) {
    __extends(ErrorHandler, _super);

    function ErrorHandler() {
      ErrorHandler.__super__.constructor.call(this, {
        objectMode: true
      });
    }

    ErrorHandler.prototype._write = function(chk, size, enc) {
      return this.push(chk);
    };

    return ErrorHandler;

  })(stream.Transform);

  module.exports = ErrorHandler;

}).call(this);
