// Generated by CoffeeScript 1.6.3
(function() {
  var LogHandler, stream,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  stream = require('stream');

  LogHandler = (function(_super) {
    __extends(LogHandler, _super);

    function LogHandler() {
      LogHandler.__super__.constructor.call(this, {
        objectMode: true
      });
    }

    LogHandler.prototype._write = function(chk, size, enc) {
      return this.push(chk);
    };

    return LogHandler;

  })(stream.Transform);

  module.exports = LogHandler;

}).call(this);
