// Generated by CoffeeScript 1.6.3
(function() {
  var TaskHandler, stream,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  stream = require('stream');

  TaskHandler = (function(_super) {
    __extends(TaskHandler, _super);

    function TaskHandler(logger, error) {
      this.logger = logger;
      this.error = error;
      TaskHandler.__super__.constructor.call(this, {
        objectMode: true
      });
      this.tasks = {};
    }

    TaskHandler.prototype._write = function(data, enc, cb) {
      return cb("TEST");
    };

    return TaskHandler;

  })(stream.Writable);

  module.exports = TaskHandler;

}).call(this);
